version: '3'
services:

  nsqlookupd:
    container_name: commons_eventbus_test_nsqlookupd
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "127.0.0.1:4160:4160"
      - "127.0.0.1:4161:4161"

  nsqd:
    container_name: commons_eventbus_test_nsqd
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - "127.0.0.1:4150:4150"
      - "127.0.0.1:4151:4151"
    links:
      - nsqlookupd

  nsqadmin:
    container_name: commons_eventbus_test_nsqadmin
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "127.0.0.1:4171:4171"
    links:
      - nsqlookupd

  redis:
    container_name: commons_eventbus_test_redis_single
    image: redis
    ports:
    - 127.0.0.1:6379:6379

