version: '3'
services:

  nsqlookupd:
    image: nsqio/nsq
    command: /nsqlookupd
    ports:
      - "127.0.0.1:4160:4160"
      - "127.0.0.1:4161:4161"

  nsqd:
    image: nsqio/nsq
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160
    ports:
      - "127.0.0.1:4150:4150"
      - "127.0.0.1:4151:4151"
    links:
      - nsqlookupd

  nsqadmin:
    image: nsqio/nsq
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
    ports:
      - "127.0.0.1:4171:4171"
    links:
      - nsqlookupd

  redis_single:
    image: redis:5
    ports:
    - 127.0.0.1:6379:6379

  redis_abort:
    image: redis:5
    restart: always
    ports:
      - 127.0.0.1:6380:6379

  mqtt-broker:
    image: library/eclipse-mosquitto:1.6
    restart: always
    ports:
      - 127.0.0.1:1883:1883
      - 127.0.0.1:9001:9001

